# https://github.com/isaacs/github/issues/415#issuecomment-769711216
name: Mirror Repos
on:
  workflow_dispatch:
  push:
    branches:    
      - main
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron: '0 0 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Prep
      run: |
        mkdir ~/.ssh/
    - name: bij1-wp-theme
      env:
        REPO: bij1-wp-theme
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.bij1_wp_theme }}
      run: |
        echo "$ACCESS_TOKEN" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git clone --mirror "https://github:$GITLAB_TOKEN@gitlab.com/bij1/$REPO.git"
        cd $REPO.git
        git remote add github "git@github.com:bij1/$REPO.git"
        git push --mirror github
