# https://github.com/isaacs/github/issues/415#issuecomment-769711216
name: Mirror Repos
on:
  workflow_dispatch:
  push:
    branches:    
      - main
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron: '0 0 * * *'

jobs:
  bij1_wp_theme:
    runs-on: ubuntu-latest
    env:
      REPO: bij1-wp-theme
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      ACCESS_TOKEN: ${{ secrets.bij1_wp_theme }}
    steps:
#     - name: Mirror
#       run: |
#         git clone --mirror "https://github:$GITLAB_TOKEN@gitlab.com/bij1/$REPO.git"
#         cd $REPO.git/
#         git remote add github "https://bij1:$ACCESS_TOKEN@github.com/$REPO.git"
#         git push --mirror github
#         cd ..
    - name: clone
      run: git clone --mirror "https://github:$GITLAB_TOKEN@gitlab.com/bij1/$REPO.git"
    - name: pwd
      run: pwd
    - name: ls
      run: ls
    - name: enter
      run: |
        echo $REPO.git
        echo '$REPO.git'
        echo "$REPO.git"
        echo "${REPO}.git"
        cd "$REPO.git"
    - name: pwd2
      run: pwd
    - name: ls2
      run: ls
    - name: add remote
      run: git remote add github "https://bij1:$ACCESS_TOKEN@github.com/$REPO.git"
    - name: push
      run: git push --mirror github
    - name: leave
      run: cd ..
