# https://github.com/isaacs/github/issues/415#issuecomment-769711216
name: Mirror Repos
on:
  workflow_dispatch:
  push:
    branches:    
      - main
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITLAB_USER: ${{ secrets.GITLAB_USER }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    steps:
    - name: Mirror
      env:
        REPO: bij1-wp-theme
        ACCESS_TOKEN: ${{ secrets.bij1_wp_theme }}
      run: |
        git clone --mirror "https://$GITLAB_USER:$GITLAB_TOKEN@gitlab.com/bij1/$REPO.git"
        cd $REPO.git/
        git remote add github "https://bij1:$ACCESS_TOKEN@github.com/$REPO.git"
        git push --mirror github
        cd ..
