# https://github.com/isaacs/github/issues/415#issuecomment-769711216
name: Mirror Repos
on:
  workflow_dispatch:
  push:
    branches:    
      - main
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron: '0 0 * * *'

jobs:
  bij1_wp_theme:
    runs-on: ubuntu-latest
    env:
      REPO: bij1-wp-theme
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      ACCESS_TOKEN: ${{ secrets.bij1_wp_theme }}
    steps:
    - name: Mirror
      run: |
        ls /home/user/.ssh/
        git clone --mirror "https://github:$GITLAB_TOKEN@gitlab.com/bij1/$REPO.git"
        cd $REPO.git
        echo "$ACCESS_TOKEN" > ~/.ssh/id_rsa
        git remote add github "git@github.com:bij1/$REPO.git"
        git push --mirror github
